version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    groups:
      eslint:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@eslint/*'
          - 'typescript-eslint'
      typescript:
        patterns:
          - 'typescript'
          - 'tsup'
          - '@types/*'
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
