import { renderActivitySvg } from '@takuhon/core';
import type { ActivitySnapshot, LocaleTag } from '@takuhon/core';

import { getUILabel } from '../lib/ui-labels.js';

import styles from './ActivitySection.module.css';

export interface ActivitySectionProps {
  /**
   * The synced developer-activity snapshot (a sibling document, not part of
   * `LocalizedTakuhon`). Hosts fetch it themselves — `GET /api/activity` on a
   * deployment, or the `activity.json` beside the profile locally.
   */
  snapshot?: ActivitySnapshot | null;
  locale?: LocaleTag;
}

/**
 * Developer-activity section: the same self-owned inline-SVG card the static
 * export renders, generated by `@takuhon/core`'s `renderActivitySvg` so the
 * two surfaces cannot drift. Renders nothing without a snapshot (or with one
 * that carries no metric data) — the section degrades away gracefully.
 */
export function ActivitySection({
  snapshot,
  locale = 'en',
}: ActivitySectionProps): React.JSX.Element | null {
  if (!snapshot) return null;
  const svg = renderActivitySvg(snapshot);
  if (svg === '') return null;

  return (
    <section className={styles.section} aria-labelledby="takuhon-activity-heading">
      <h2 id="takuhon-activity-heading" className={styles.heading}>
        {getUILabel('section.activity', locale)}
      </h2>
      {/* The markup is produced entirely by core's renderActivitySvg, which
          XML-escapes every snapshot-derived value (language names are external
          API data); no raw input ever reaches this sink. */}
      <div className={styles.card} dangerouslySetInnerHTML={{ __html: svg }} />
    </section>
  );
}
